sudo: required
services:
         - docker
before_install:
         - docker build -t aswala/docker-react -f Dockerfile.dev .
script:
         - docker run aswala/docker-react npm run test -- --coverage
deploy:
         provider: elasticbeanstalk
         region: "us-east-2"
         app: docker
         env: Docker-env
         bucket_name: "elasticbeanstalk-us-east-2-907056319030"
         bucket_path: "docker"
         on:
            branch: master
         access_key_id: $Accesskey_AWS
         secret_access_key:
            secure: "$SECRETKEY_AWS"
         
