sudo: required
services:
         - docker
before_install:
         - docker build -t aswala/docker-react -f Dockerfile.dev .
script:
         - docker run aswala/docker-react npm run test -- --coverage
